//img
import cottage from '../assets/img/offers/cottage.jpg'
import hotel from '../assets/img/offers/hotel.jpg'
import apartament from '../assets/img/offers/apartament.jpg'

export const PRODUCTS = [
  {
    id: 0,
    cityValue: 'zakopane',
    placeValue: 'cottage',
    img: cottage,
    title: 'Lorem ipsum dolor sit amet',
    adress: 'Zakopane',
    place: 'Domek',
    price: '47',
  },
  {
    id: 1,
    cityValue: 'zakopane',
    placeValue: 'cottage',
    img: cottage,
    title: 'Lorem ipsum dolor sit amet',
    adress: 'Zakopane',
    place: 'Domek',
    price: '34',
  },
  {
    id: 2,
    cityValue: 'zakopane',
    placeValue: 'cottage',
    img: cottage,
    title: 'Lorem ipsum dolor sit amet',
    adress: 'Zakopane',
    place: 'Domek',
    price: '39',
  },
  {
    id: 3,
    cityValue: 'zakopane',
    placeValue: 'hotel',
    img: hotel,
    title: 'Lorem ipsum dolor sit amet',
    adress: 'Zakopane',
    place: 'Hotel',
    price: '89',
  },
  {
    id: 4,
    cityValue: 'zakopane',
    placeValue: 'hotel',
    img: hotel,
    title: 'Lorem ipsum dolor sit amet',
    adress: 'Zakopane',
    place: 'Hotel',
    price: '99',
  },
  {
    id: 5,
    cityValue: 'wroclaw',
    placeValue: 'cottage',
    img: cottage,
    title: 'Lorem ipsum dolor sit amet',
    adress: 'Wrocław',
    place: 'Domek',
    price: '59',
  },
  {
    id: 6,
    cityValue: 'wroclaw',
    placeValue: 'hotel',
    img: hotel,
    title: 'Lorem ipsum dolor sit amet',
    adress: 'Wrocław',
    place: 'Hotel',
    price: '95',
  },
  {
    id: 7,
    cityValue: 'wroclaw',
    placeValue: 'hotel',
    img: hotel,
    title: 'Lorem ipsum dolor sit amet',
    adress: 'Wrocław',
    place: 'Hotel',
    price: '66',
  },
  {
    id: 8,
    cityValue: 'wroclaw',
    placeValue: 'hotel',
    img: hotel,
    title: 'Lorem ipsum dolor sit amet',
    adress: 'Wrocław',
    place: 'Hotel',
    price: '99',
  },
  {
    id: 9,
    cityValue: 'wroclaw',
    placeValue: 'apartament',
    img: apartament,
    title: 'Lorem ipsum dolor sit amet',
    adress: 'Wrocław',
    place: 'Apartament',
    price: '101',
  },
  {
    id: 10,
    cityValue: 'szczecin',
    placeValue: 'hotel',
    img: hotel,
    title: 'Lorem ipsum dolor sit amet',
    adress: 'Szczecin',
    place: 'Hotel',
    price: '89',
  },
  {
    id: 11,
    cityValue: 'szczecin',
    placeValue: 'hotel',
    img: hotel,
    title: 'Lorem ipsum dolor sit amet',
    adress: 'Szczecin',
    place: 'Hotel',
    price: '69',
  },
  {
    id: 12,
    cityValue: 'szczecin',
    placeValue: 'apartament',
    img: apartament,
    title: 'Lorem ipsum dolor sit amet',
    adress: 'Szczecin',
    place: 'Apartament',
    price: '129',
  },
  {
    id: 13,
    cityValue: 'gdansk',
    placeValue: 'hotel',
    img: hotel,
    title: 'Lorem ipsum dolor sit amet',
    adress: 'Gdańsk',
    place: 'Hotel',
    price: '99',
  },
  {
    id: 14,
    cityValue: 'gdansk',
    placeValue: 'apartament',
    img: apartament,
    title: 'Lorem ipsum dolor sit amet',
    adress: 'Gdańsk',
    place: 'Apartament',
    price: '99',
  },
  {
    id: 15,
    cityValue: 'gdansk',
    placeValue: 'apartament',
    img: apartament,
    title: 'Lorem ipsum dolor sit amet',
    adress: 'Gdańsk',
    place: 'Apartament',
    price: '109',
  },
  {
    id: 16,
    cityValue: 'gdansk',
    placeValue: 'apartament',
    img: apartament,
    title: 'Lorem ipsum dolor sit amet',
    adress: 'Gdańsk',
    place: 'Apartament',
    price: '129',
  },
  {
    id: 17,
    cityValue: 'szczecin',
    placeValue: 'apartament',
    img: apartament,
    title: 'Lorem ipsum dolor sit amet',
    adress: 'Gdańsk',
    place: 'Apartament',
    price: '85',
  },
  {
    id: 18,
    cityValue: 'solina',
    placeValue: 'cottage',
    img: cottage,
    title: 'Lorem ipsum dolor sit amet',
    adress: 'Solina',
    place: 'Domek',
    price: '39',
  },
  {
    id: 19,
    cityValue: 'solina',
    placeValue: 'cottage',
    img: cottage,
    title: 'Lorem ipsum dolor sit amet',
    adress: 'Solina',
    place: 'Domek',
    price: '49',
  },
  {
    id: 20,
    cityValue: 'solina',
    placeValue: 'hotel',
    img: apartament,
    title: 'Lorem ipsum dolor sit amet',
    adress: 'Solina',
    place: 'Hotel',
    price: '79',
  },
]