//img
import house from '../assets/img/offers/house.jpg'
import hotel from '../assets/img/offers/hotel.jpg'
import apartament from '../assets/img/offers/apartament.jpg'

export const PRODUCTS = [
  //cityValue: 0-Wrocław; 1-Zakopane; 2-Szczecin; 3-Gdańsk; 4-Solina; 
  //placeValue: 0-Domek; 1-Hotel; 2-Apartament;

  {
    id: 0,
    cityValue: 1,
    placeValue: 0,
    img: house,
    title: 'Lorem ipsum dolor sit amet',
    adress: 'Zakopane',
    place: 'Domek',
    price: '47',
  },
  {
    id: 1,
    cityValue: 1,
    placeValue: 0,
    img: house,
    title: 'Lorem ipsum dolor sit amet',
    adress: 'Zakopane',
    place: 'Domek',
    price: '34',
  },
  {
    id: 2,
    cityValue: 1,
    placeValue: 0,
    img: house,
    title: 'Lorem ipsum dolor sit amet',
    adress: 'Zakopane',
    place: 'Domek',
    price: '39',
  },
  {
    id: 3,
    cityValue: 1,
    placeValue: 1,
    img: hotel,
    title: 'Lorem ipsum dolor sit amet',
    adress: 'Zakopane',
    place: 'Hotel',
    price: '89',
  },
  {
    id: 4,
    cityValue: 1,
    placeValue: 1,
    img: hotel,
    title: 'Lorem ipsum dolor sit amet',
    adress: 'Zakopane',
    place: 'Hotel',
    price: '99',
  },
  {
    id: 5,
    cityValue: 0,
    placeValue: 0,
    img: house,
    title: 'Lorem ipsum dolor sit amet',
    adress: 'Wrocław',
    place: 'Domek',
    price: '59',
  },
  {
    id: 6,
    cityValue: 0,
    placeValue: 1,
    img: hotel,
    title: 'Lorem ipsum dolor sit amet',
    adress: 'Hotel',
    place: 'Domek',
    price: '95',
  },
  {
    id: 7,
    cityValue: 0,
    placeValue: 1,
    img: hotel,
    title: 'Lorem ipsum dolor sit amet',
    adress: 'Wrocław',
    place: 'Hotel',
    price: '66',
  },
  {
    id: 8,
    cityValue: 0,
    placeValue: 1,
    img: hotel,
    title: 'Lorem ipsum dolor sit amet',
    adress: 'Wrocław',
    place: 'Hotel',
    price: '99',
  },
  {
    id: 9,
    cityValue: 0,
    placeValue: 2,
    img: apartament,
    title: 'Lorem ipsum dolor sit amet',
    adress: 'Wrocław',
    place: 'Apartament',
    price: '101',
  },
  {
    id: 10,
    cityValue: 2,
    placeValue: 1,
    img: hotel,
    title: 'Lorem ipsum dolor sit amet',
    adress: 'Szczecin',
    place: 'Hotel',
    price: '89',
  },
  {
    id: 11,
    cityValue: 2,
    placeValue: 1,
    img: hotel,
    title: 'Lorem ipsum dolor sit amet',
    adress: 'Szczecin',
    place: 'Hotel',
    price: '69',
  },
  {
    id: 12,
    cityValue: 2,
    placeValue: 2,
    img: apartament,
    title: 'Lorem ipsum dolor sit amet',
    adress: 'Szczecin',
    place: 'Apartament',
    price: '129',
  },
  {
    id: 13,
    cityValue: 3,
    placeValue: 1,
    img: hotel,
    title: 'Lorem ipsum dolor sit amet',
    adress: 'Gdańsk',
    place: 'Hotel',
    price: '99',
  },
  {
    id: 14,
    cityValue: 3,
    placeValue: 2,
    img: apartament,
    title: 'Lorem ipsum dolor sit amet',
    adress: 'Gdańsk',
    place: 'Apartament',
    price: '99',
  },
  {
    id: 15,
    cityValue: 3,
    placeValue: 2,
    img: apartament,
    title: 'Lorem ipsum dolor sit amet',
    adress: 'Gdańsk',
    place: 'Apartament',
    price: '109',
  },
  {
    id: 16,
    cityValue: 3,
    placeValue: 2,
    img: apartament,
    title: 'Lorem ipsum dolor sit amet',
    adress: 'Gdańsk',
    place: 'Apartament',
    price: '129',
  },
  {
    id: 17,
    cityValue: 2,
    placeValue: 2,
    img: apartament,
    title: 'Lorem ipsum dolor sit amet',
    adress: 'Gdańsk',
    place: 'Apartament',
    price: '85',
  },
  {
    id: 18,
    cityValue: 4,
    placeValue: 0,
    img: house,
    title: 'Lorem ipsum dolor sit amet',
    adress: 'Solina',
    place: 'Domek',
    price: '39',
  },
  {
    id: 19,
    cityValue: 4,
    placeValue: 0,
    img: house,
    title: 'Lorem ipsum dolor sit amet',
    adress: 'Solina',
    place: 'Domek',
    price: '49',
  },
  {
    id: 20,
    cityValue: 4,
    placeValue: 1,
    img: apartament,
    title: 'Lorem ipsum dolor sit amet',
    adress: 'Solina',
    place: 'Hotel',
    price: '79',
  },
]